name: Merge develop into staging
on:
  push:
    branches:
      - "develop"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge develop into staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: staging
          message: Automated merge 'develop' into 'staging'
          github_token: ${{ secrets.ACTION_MERGE }}
